source 'https://rubygems.org'
gem "bundler"
gem "jekyll"
gem "jekyll-paginate"
gem "jekyll-sitemap"
gem "csv"
gem "logger"
gem "builder"
gem "webrick"
# source "https://rubygems.org"

# gem "jekyll", "~> 4.3"
# gem "csv"
# gem "logger"
# gem "builder"